#!/bin/bash

# Argument = -i ip-address -d dockerfile -p port

usage()
{
  cat << EOF
usage: $0 options

This script deploys dockerfile code to IP address and port.

OPTIONS:
  -i      IP Address
  -d      Path To Dockerfile
  -p      Port
  -k      Path To SSH Key (Optional Default $HOME/.ssh/id_rsa only required first time running)
  -e      Enviornment Variables to set (-e key1=value1 -e key2=value2)
  -f      folder to include
EOF
}

IP=
DOCKER_FILE_LOCATION=
PORT=
SSH_KEY=$HOME/.ssh/id_rsa
ENV_COMMAND=
FILE_INCLUDE=
IMPORT_FOLDER=/.tmp

while getopts i:d:p:e:f:k:: OPTION; do
  case $OPTION in
    i)
      IP=$OPTARG
      ;;
    d)
      DOCKER_FILE_LOCATION=$OPTARG
      ;;
    p)
      PORT=$OPTARG
      ;;
    k)
      SSH_KEY=$OPTARG
      ;;
    e)
      ENV_COMMAND+="--env "$OPTARG" "
      ;;
    f)
      FILE_INCLUDE=$OPTARG
      ;;
    ?)
      usage
      exit
      ;;
   esac
done

if [[ -z $IP ]] || [[ -z $DOCKER_FILE_LOCATION ]] || [[ -z $PORT ]]
then
  usage
  exit 1
fi

echo "IP" = $IP
echo "DOCKER_FILE_LOCATION" = $DOCKER_FILE_LOCATION
echo "PORT" = $PORT
echo "SSH_KEY" = $SSH_KEY
echo "ENV_COMMAND" = $ENV_COMMAND
echo "FILE_INCLUDE" = $FILE_INCLUDE

MACHINE_NAME=$IP-machine
IMAGE_NAME=$IP`echo ${DOCKER_FILE_LOCATION} | tr '[:upper:]' '[:lower:]' | sed "s/\//_/g"`

echo "IMAGE_NAME" = $IMAGE_NAME
echo "MACHINE_NAME" = $MACHINE_NAME

docker-machine create  --driver generic --generic-ip-address $IP $MACHINE_NAME --generic-ssh-key $SSH_KEY
eval "$(docker-machine env $MACHINE_NAME)"
docker build --rm -t $IMAGE_NAME $DOCKER_FILE_LOCATION
docker run -d -p $PORT:80 --env 'CLIENT_IP='$IP --env 'HOST_PORT='$PORT --env 'IMPORT_FOLDER='$IMPORT_FOLDER $ENV_COMMAND $IMAGE_NAME
echo docker run -d -p $PORT:80 --env 'CLIENT_IP='$IP --env 'HOST_PORT='$PORT --env 'IMPORT_FOLDER='$IMPORT_FOLDER $ENV_COMMAND $IMAGE_NAME
docker-machine ssh $MACHINE_NAME "sudo mkdir -p $IMPORT_FOLDER"
if [[ -n $FILE_INCLUDE ]]; then
  docker-machine scp $FILE_INCLUDE $MACHINE_NAME:$IMPORT_FOLDER
fi
