#!/bin/bash

# Argument = -i ip-address -d dockerfile -p port

usage()
{
  cat << EOF
usage: $0 options

This script deploys dockerfile code to IP address and port.

OPTIONS:
  -i      IP Address
  -d      Path To Dockerfile
  -p      Port
  -k      Path To SSH Key (Optional Default $HOME/.ssh/id_rsa only required first time running)
  -e      Enviornment Variables to set (-e key1=value1 -e key2=value2)
  -f      files to include (-f /filename1 -f /filename2)
EOF
}

EXPOSE_PORT=443

IP=
DOCKER_FILE_LOCATION=
PORT=
SSH_KEY=$HOME/.ssh/id_rsa
ENV_COMMAND=
FILES_INCLUDE=

while getopts i:d:p:e:f:k:: OPTION; do
  case $OPTION in
    i)
      IP=$OPTARG
      ;;
    d)
      DOCKER_FILE_LOCATION=$OPTARG
      ;;
    p)
      PORT=$OPTARG
      ;;
    k)
      SSH_KEY=$OPTARG
      ;;
    e)
      ENV_COMMAND+="--env "$OPTARG" "
      ;;
    f)
      FILES_INCLUDE+=$OPTARG" "
      ;;
    ?)
      usage
      exit
      ;;
   esac
done

if [[ -z $IP ]] || [[ -z $DOCKER_FILE_LOCATION ]] || [[ -z $PORT ]]
then
  usage
  exit 1
fi

IMPORT_FOLDER=/.tmp$PORT

echo "IP" = $IP
echo "DOCKER_FILE_LOCATION" = $DOCKER_FILE_LOCATION
echo "PORT" = $PORT
echo "SSH_KEY" = $SSH_KEY
echo "ENV_COMMAND" = $ENV_COMMAND
echo "FILES_INCLUDE" = $FILES_INCLUDE
echo "IMPORT_FOLDER" = $IMPORT_FOLDER

MACHINE_NAME=$IP-machine
IMAGE_NAME=$IP`echo ${DOCKER_FILE_LOCATION} | tr '[:upper:]' '[:lower:]' | sed "s/\//_/g"`

echo "IMAGE_NAME" = $IMAGE_NAME
echo "MACHINE_NAME" = $MACHINE_NAME

docker-machine create  --driver generic --generic-ip-address $IP $MACHINE_NAME --generic-ssh-key $SSH_KEY
eval "$(docker-machine env $MACHINE_NAME)"
docker build --rm -t $IMAGE_NAME $DOCKER_FILE_LOCATION
docker-machine ssh $MACHINE_NAME "sudo mkdir -p $IMPORT_FOLDER"
if [[ -n $FILES_INCLUDE ]]; then
  docker-machine scp $FILES_INCLUDE $MACHINE_NAME:$IMPORT_FOLDER
fi
CONTAINER_VOLUME=/mnt

echo docker run -d -p $PORT:$EXPOSE_PORT -v $IMPORT_FOLDER:$CONTAINER_VOLUME:ro -e 'HOST_IP='$IP -e 'HOST_PORT='$PORT -e 'CONTAINER_VOLUME='$CONTAINER_VOLUME $ENV_COMMAND $IMAGE_NAME
docker run -d -p $PORT:$EXPOSE_PORT -v $IMPORT_FOLDER:$CONTAINER_VOLUME:ro -e 'HOST_IP='$IP -e 'HOST_PORT='$PORT -e 'CONTAINER_VOLUME='$CONTAINER_VOLUME $ENV_COMMAND $IMAGE_NAME

echo "DONE!!!"