#!/bin/bash

# Argument = -i ip-address -d dockerfile -p port

usage()
{
  cat << EOF
usage: $0 options

This script deploys dockerfile code to IP address and port.

OPTIONS:
  -m      Machine Name
  -d      Path To Dockerfile
  -p      Port
  -e      Enviornment Variables to set (-e key1=value1 -e key2=value2)
  -f      files to include (-f /filename1 -f /filename2)
EOF
}

EXPOSE_PORT=443

MACHINE_NAME=
DOCKER_FILE_LOCATION=
PORT=
ENV_COMMAND=
FILES_INCLUDE=

while getopts m:d:p:e:f: OPTION; do
  case $OPTION in
    m)
      MACHINE_NAME=$OPTARG
      ;;
    d)
      DOCKER_FILE_LOCATION=$OPTARG
      ;;
    p)
      PORT=$OPTARG
      ;;
    e)
      ENV_COMMAND+="-e "$OPTARG" "
      ;;
    f)
      FILES_INCLUDE+=$OPTARG" "
      ;;
    ?)
      usage
      exit
      ;;
   esac
done

if [[ -z $MACHINE_NAME ]] || [[ -z $DOCKER_FILE_LOCATION ]] || [[ -z $PORT ]]
then
  usage
  exit 1
fi

IMPORT_FOLDER=/.tmp$PORT

echo "MACHINE_NAME" = $MACHINE_NAME
echo "DOCKER_FILE_LOCATION" = $DOCKER_FILE_LOCATION
echo "PORT" = $PORT
echo "ENV_COMMAND" = $ENV_COMMAND
echo "FILES_INCLUDE" = $FILES_INCLUDE
echo "IMPORT_FOLDER" = $IMPORT_FOLDER

IMAGE_NAME=$MACHINE_NAME`echo ${DOCKER_FILE_LOCATION} | tr '[:upper:]' '[:lower:]' | sed "s/\//_/g"`

echo "IMAGE_NAME" = $IMAGE_NAME


docker-machine create  --driver virtualbox $MACHINE_NAME 
eval "$(docker-machine env $MACHINE_NAME)"
docker build --rm -t $IMAGE_NAME $DOCKER_FILE_LOCATION

IP=`docker-machine ip $MACHINE_NAME`

echo "IP" = $IP

docker-machine ssh $MACHINE_NAME "sudo mkdir -p $IMPORT_FOLDER"
docker-machine ssh $MACHINE_NAME "sudo chown docker:staff $IMPORT_FOLDER"

if [[ -n $FILES_INCLUDE ]]; then
  docker-machine scp $FILES_INCLUDE $MACHINE_NAME:$IMPORT_FOLDER
fi

CONTAINER_VOLUME=/mnt

echo docker run -d -p $PORT:$EXPOSE_PORT -v $IMPORT_FOLDER:$CONTAINER_VOLUME:ro -e 'HOST_PORT='$PORT -e 'CONTAINER_VOLUME='$CONTAINER_VOLUME -e "HOST_IP="$IP $ENV_COMMAND $IMAGE_NAME
docker run -d -p $PORT:$EXPOSE_PORT -v $IMPORT_FOLDER:$CONTAINER_VOLUME:ro -e 'HOST_PORT='$PORT -e 'CONTAINER_VOLUME='$CONTAINER_VOLUME -e "HOST_IP="$IP $ENV_COMMAND $IMAGE_NAME

echo "DONE!!!"

